# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 14 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "dadi" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6a14fc996062bfd7bcfda5a08177458fc12dd2e14dda5d78f94e91db32d97b45
  # sha256 is the preferred checksum -- you can get it for a file with:
  #  `openssl sha256 <file name>`.

build:
  number: 0
  script: 'rm */*/*.so && {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --install-option="--cython" '

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - cython
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib

test:
  imports:
    - dadi
    - dadi.DFE
    - dadi.Triallele
    - dadi.TwoLocus

about:
  home: "https://bitbucket.org/gutenkunstlab/dadi"
  license: "BSD-3-Clause"
  license_family: "BSD"
  license_file: "LICENSE.txt"
  summary: "Fit population genetic models using diffusion approximations to the allele frequency spectrum"
  doc_url: "https://dadi.readthedocs.io/"

extra:
  recipe-maintainers:
    - RyanGutenkunst
